name: Rust

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: '00 01 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pre-deps
        run: sudo apt-get install libasound2-dev libdbus-1-dev

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Run Clippy Correctness lints
        run: cargo clippy -- -D clippy::correctness


      - name: Build Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -Z strip=symbols

      - name: Set GIT_TAG env
        run: echo ::set-env name=GIT_TAG::$(echo ${GITHUB_REF:10})
      - name: Create tmp dir
        if: startsWith(github.ref, 'refs/tags/')
        run: mkdir /tmp/build_result
      - name: Package Release
        if: startsWith(github.ref, 'refs/tags/')
        run: cd target/release && tar -czvf pomo-break.tar.gz pomo-break
      - name: Copy Package
        if: startsWith(github.ref, 'refs/tags/')
        run: cp target/release/pomo-break.tar.gz /tmp/build_result/pomo-break-$GIT_TAG.tar.gz

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          files: /tmp/build_result/pomo-break*.tar.gz
